### ISSUE TITLE
Maybe call it `go-ast`?

### ISSUE THREAD

**Issue by alichtman** [cretz/go-dump#1]
Or `ghost`, if you're okay giving up the `go` reference.

**Comment by cretz** [comment]
Really just a tool for another project I was considering. Using `go-dump` let's the imported package be `dump` as opposed to `ast` which would be ambiguous with the stdlib package of the same name. I'll keep this one for now, but if it becomes popular I'll give it something more clever :-) (closing, but leaving comments open)
